apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Tue, 08 Feb 2022 15:46:46 UTC
        provider: minikube.sigs.k8s.io
        version: v1.18.0
      name: cluster_info
    server: https://172.17.0.24:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 08 Feb 2022 15:46:46 UTC
        provider: minikube.sigs.k8s.io
        version: v1.18.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/profiles/minikube/client.crt
    client-key: /root/.minikube/profiles/minikube/client.key