apiVersion: v1
kind: Service
metadata:
  name: teastore-webui
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: http-teastore
  selector:
    app: teastore
  sessionAffinity: None
  type: LoadBalancer