name: Docker Image CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build-Image
      run: |
        docker build -t ghcr.io/cannavit/test:latest -f Dockerfile .  
        export CR_PAT=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
        echo $CR_PAT | docker login ghcr.io -u cannavit --password-stdin
        docker push ghcr.io/cannavit/test:latest
        
