name: Docker Image CI

on:
  push:
    branches:
    - develop
  pull_request:

# jobs:
#   build:
#     name: 'Build'
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Build:checkout"
#         uses: actions/checkout@v2
#       - name: 'Build:dockerimage'
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.PAT }}
#           repository: cannavit/test:develop
# #           tags: latest
#           push: ${{ GitHub.event_name != 'pull_request' }}
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
          
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
