name: Docker Image CI

on:
  push:
    branches:
    - develop
  pull_request:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v2
        with:
          context: .
          registry: ghcr.io
          username: "cannavit"
          password: ${{ secrets.PAT }}
          repository: cannavit/test:develop
#           tags: latest
          push: ${{ GitHub.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
